
let companies = [
  { symbol: "MMM", name: "3M Company" },
  { symbol: "ABT", name: "Abbott Laboratories" },
  { symbol: "ABBV", name: "AbbVie Inc." },
  { symbol: "ABMD", name: "ABIOMED Inc" },
  { symbol: "ACN", name: "Accenture plc" },
  { symbol: "ATVI", name: "Activision Blizzard" },
  { symbol: "ADBE", name: "Adobe Systems Inc" },
  { symbol: "AMD", name: "Advanced Micro Devices Inc" },
  { symbol: "AAP", name: "Advance Auto Parts" },
  { symbol: "AES", name: "AES Corp" },
  { symbol: "AMG", name: "Affiliated Managers Group Inc" },
  { symbol: "AFL", name: "AFLAC Inc" },
  { symbol: "A", name: "Agilent Technologies Inc" },
  { symbol: "APD", name: "Air Products & Chemicals Inc" },
  { symbol: "AKAM", name: "Akamai Technologies Inc" },
  { symbol: "ALK", name: "Alaska Air Group Inc" },
  { symbol: "ALB", name: "Albemarle Corp" },
  { symbol: "ARE", name: "Alexandria Real Estate Equities" },
  { symbol: "ALXN", name: "Alexion Pharmaceuticals" },
  { symbol: "ALGN", name: "Align Technology" },
  { symbol: "ALLE", name: "Allegion" },
  { symbol: "AGN", name: "Allergan, Plc" },
  { symbol: "ADS", name: "Alliance Data Systems" },
  { symbol: "LNT", name: "Alliant Energy Corp" },
  { symbol: "ALL", name: "Allstate Corp" },
  { symbol: "GOOGL", name: "Alphabet Inc Class A" },
  { symbol: "GOOG", name: "Alphabet Inc Class C" },
  { symbol: "MO", name: "Altria Group Inc" },
  { symbol: "AMZN", name: "Amazon.com Inc." },
  { symbol: "AMCR", name: "Amcor plc" },
  { symbol: "AEE", name: "Ameren Corp" },
  { symbol: "AAL", name: "American Airlines Group" },
  { symbol: "AEP", name: "American Electric Power" },
  { symbol: "AXP", name: "American Express Co" },
  { symbol: "AIG", name: "American International Group" },
  { symbol: "AMT", name: "American Tower Corp." },
  { symbol: "AWK", name: "American Water Works Company Inc" },
  { symbol: "AMP", name: "Ameriprise Financial" },
  { symbol: "ABC", name: "AmerisourceBergen Corp" },
  { symbol: "AME", name: "AMETEK Inc." },
  { symbol: "AMGN", name: "Amgen Inc." },
  { symbol: "APH", name: "Amphenol Corp" },
  { symbol: "ADI", name: "Analog Devices, Inc." },
  { symbol: "ANSS", name: "ANSYS" },
  { symbol: "ANTM", name: "Anthem" },
  { symbol: "AON", name: "Aon plc" },
  { symbol: "AOS", name: "A.O. Smith Corp" },
  { symbol: "APA", name: "Apache Corporation" },
  { symbol: "AIV", name: "Apartment Investment & Management" },
  { symbol: "AAPL", name: "Apple Inc." },
  { symbol: "AMAT", name: "Applied Materials Inc." },
  { symbol: "APTV", name: "Aptiv Plc" },
  { symbol: "ADM", name: "Archer-Daniels-Midland Co" },
  { symbol: "ARNC", name: "Arconic Inc." },
  { symbol: "ANET", name: "Arista Networks" },
  { symbol: "AJG", name: "Arthur J. Gallagher & Co." },
  { symbol: "AIZ", name: "Assurant" },
  { symbol: "ATO", name: "Atmos Energy Corp" },
  { symbol: "T", name: "AT&T Inc." },
  { symbol: "ADSK", name: "Autodesk Inc." },
  { symbol: "ADP", name: "Automatic Data Processing" },
  { symbol: "AZO", name: "AutoZone Inc" },
  { symbol: "AVB", name: "AvalonBay Communities, Inc." },
  { symbol: "AVY", name: "Avery Dennison Corp" },
  { symbol: "BHGE", name: "Baker Hughes, a GE Company" },
  { symbol: "BLL", name: "Ball Corp" },
  { symbol: "BAC", name: "Bank of America Corp" },
  { symbol: "BK", name: "The Bank of New York Mellon Corp." },
  { symbol: "BAX", name: "Baxter International Inc." },
  { symbol: "BBT", name: "BB&T Corporation" },
  { symbol: "BDX", name: "Becton Dickinson" },
  { symbol: "BRK.B", name: "Berkshire Hathaway" },
  { symbol: "BBY", name: "Best Buy Co. Inc." },
  { symbol: "BIIB", name: "Biogen Inc." },
  { symbol: "BLK", name: "BlackRock" },
  { symbol: "HRB", name: "Block H&R" },
  { symbol: "BA", name: "Boeing Company" },
  { symbol: "BKNG", name: "Booking Holdings Inc" },
  { symbol: "BWA", name: "BorgWarner" },
  { symbol: "BXP", name: "Boston Properties" },
  { symbol: "BSX", name: "Boston Scientific" },
  { symbol: "BMY", name: "Bristol-Myers Squibb" },
  { symbol: "AVGO", name: "Broadcom Inc." },
  { symbol: "BR", name: "Broadridge Financial Solutions" },
  { symbol: "BF.B", name: "Brown-Forman Corp." },
  { symbol: "CHRW", name: "C. H. Robinson Worldwide" },
  { symbol: "COG", name: "Cabot Oil & Gas" },
  { symbol: "CDNS", name: "Cadence Design Systems" },
  { symbol: "CPB", name: "Campbell Soup" },
  { symbol: "COF", name: "Capital One Financial" },
  { symbol: "CPRI", name: "Capri Holdings" },
  { symbol: "CAH", name: "Cardinal Health Inc." },
  { symbol: "KMX", name: "Carmax Inc" },
  { symbol: "CCL", name: "Carnival Corp." },
  { symbol: "CAT", name: "Caterpillar Inc." },
  { symbol: "CBOE", name: "Cboe Global Markets" },
  { symbol: "CBRE", name: "CBRE Group" },
  { symbol: "CBS", name: "CBS Corp." },
  { symbol: "CE", name: "Celanese" },
  { symbol: "CELG", name: "Celgene Corp." },
  { symbol: "CNC", name: "Centene Corporation" },
  { symbol: "CNP", name: "CenterPoint Energy" },
  { symbol: "CTL", name: "CenturyLink Inc" },
  { symbol: "CERN", name: "Cerner" },
  { symbol: "CF", name: "CF Industries Holdings Inc" },
  { symbol: "SCHW", name: "Charles Schwab Corporation" },
  { symbol: "CHTR", name: "Charter Communications" },
  { symbol: "CVX", name: "Chevron Corp." },
  { symbol: "CMG", name: "Chipotle Mexican Grill" },
  { symbol: "CB", name: "Chubb Limited" },
  { symbol: "CHD", name: "Church & Dwight" },
  { symbol: "CI", name: "CIGNA Corp." },
  { symbol: "XEC", name: "Cimarex Energy" },
  { symbol: "CINF", name: "Cincinnati Financial" },
  { symbol: "CTAS", name: "Cintas Corporation" },
  { symbol: "CSCO", name: "Cisco Systems" },
  { symbol: "C", name: "Citigroup Inc." },
  { symbol: "CFG", name: "Citizens Financial Group" },
  { symbol: "CTXS", name: "Citrix Systems" },
  { symbol: "CLX", name: "The Clorox Company" },
  { symbol: "CME", name: "CME Group Inc." },
  { symbol: "CMS", name: "CMS Energy" },
  { symbol: "KO", name: "Coca-Cola Company" },
  { symbol: "CTSH", name: "Cognizant Technology Solutions" },
  { symbol: "CL", name: "Colgate-Palmolive" },
  { symbol: "CMCSA", name: "Comcast Corp." },
  { symbol: "CMA", name: "Comerica Inc." },
  { symbol: "CAG", name: "Conagra Brands" },
  { symbol: "CXO", name: "Concho Resources" },
  { symbol: "COP", name: "ConocoPhillips" },
  { symbol: "ED", name: "Consolidated Edison" },
  { symbol: "STZ", name: "Constellation Brands" },
  { symbol: "COO", name: "The Cooper Companies" },
  { symbol: "CPRT", name: "Copart Inc" },
  { symbol: "GLW", name: "Corning Inc." },
  { symbol: "CTVA", name: "Corteva" },
  { symbol: "COST", name: "Costco Wholesale Corp." },
  { symbol: "COTY", name: "Coty, Inc" },
  { symbol: "CCI", name: "Crown Castle International Corp." },
  { symbol: "CSX", name: "CSX Corp." },
  { symbol: "CMI", name: "Cummins Inc." },
  { symbol: "CVS", name: "CVS Health" },
  { symbol: "DHI", name: "D. R. Horton" },
  { symbol: "DHR", name: "Danaher Corp." },
  { symbol: "DRI", name: "Darden Restaurants" },
  { symbol: "DVA", name: "DaVita Inc." },
  { symbol: "DE", name: "Deere & Co." },
  { symbol: "DAL", name: "Delta Air Lines Inc." },
  { symbol: "XRAY", name: "Dentsply Sirona" },
  { symbol: "DVN", name: "Devon Energy" },
  { symbol: "FANG", name: "Diamondback Energy" },
  { symbol: "DLR", name: "Digital Realty Trust Inc" },
  { symbol: "DFS", name: "Discover Financial Services" },
  { symbol: "DISCA", name: "Discovery Inc. Class A" },
  { symbol: "DISCK", name: "Discovery Inc. Class C" },
  { symbol: "DISH", name: "Dish Network" },
  { symbol: "DG", name: "Dollar General" },
  { symbol: "DLTR", name: "Dollar Tree" },
  { symbol: "D", name: "Dominion Energy" },
  { symbol: "DOV", name: "Dover Corp." },
  { symbol: "DOW", name: "Dow Inc." },
  { symbol: "DTE", name: "DTE Energy Co." },
  { symbol: "DUK", name: "Duke Energy" },
  { symbol: "DRE", name: "Duke Realty Corp" },
  { symbol: "DD", name: "DuPont de Nemours Inc" },
  { symbol: "DXC", name: "DXC Technology" },
  { symbol: "ETFC", name: "E*Trade" },
  { symbol: "EMN", name: "Eastman Chemical" },
  { symbol: "ETN", name: "Eaton Corporation" },
  { symbol: "EBAY", name: "eBay Inc." },
  { symbol: "ECL", name: "Ecolab Inc." },
  { symbol: "EIX", name: "Edison Int'l" },
  { symbol: "EW", name: "Edwards Lifesciences" },
  { symbol: "EA", name: "Electronic Arts" },
  { symbol: "EMR", name: "Emerson Electric Company" },
  { symbol: "ETR", name: "Entergy Corp." },
  { symbol: "EOG", name: "EOG Resources" },
  { symbol: "EFX", name: "Equifax Inc." },
  { symbol: "EQIX", name: "Equinix" },
  { symbol: "EQR", name: "Equity Residential" },
  { symbol: "ESS", name: "Essex Property Trust, Inc." },
  { symbol: "EL", name: "Estee Lauder Cos." },
  { symbol: "EVRG", name: "Evergy" },
  { symbol: "ES", name: "Eversource Energy" },
  { symbol: "RE", name: "Everest Re Group Ltd." },
  { symbol: "EXC", name: "Exelon Corp." },
  { symbol: "EXPE", name: "Expedia Group" },
  { symbol: "EXPD", name: "Expeditors" },
  { symbol: "EXR", name: "Extra Space Storage" },
  { symbol: "XOM", name: "Exxon Mobil Corp." },
  { symbol: "FFIV", name: "F5 Networks" },
  { symbol: "FB", name: "Facebook, Inc." },
  { symbol: "FAST", name: "Fastenal Co" },
  { symbol: "FRT", name: "Federal Realty Investment Trust" },
  { symbol: "FDX", name: "FedEx Corporation" },
  { symbol: "FIS", name: "Fidelity National Information Services" },
  { symbol: "FITB", name: "Fifth Third Bancorp" },
  { symbol: "FE", name: "FirstEnergy Corp" },
  { symbol: "FRC", name: "First Republic Bank" },
  { symbol: "FISV", name: "Fiserv Inc" },
  { symbol: "FLT", name: "FleetCor Technologies Inc" },
  { symbol: "FLIR", name: "FLIR Systems" },
  { symbol: "FLS", name: "Flowserve Corporation" },
  { symbol: "FMC", name: "FMC Corporation" },
  { symbol: "F", name: "Ford Motor" },
  { symbol: "FTNT", name: "Fortinet" },
  { symbol: "FTV", name: "Fortive Corp" },
  { symbol: "FBHS", name: "Fortune Brands Home & Security" },
  { symbol: "FOXA", name: "Fox Corporation Class A" },
  { symbol: "FOX", name: "Fox Corporation Class B" },
  { symbol: "BEN", name: "Franklin Resources" },
  { symbol: "FCX", name: "Freeport-McMoRan Inc." },
  { symbol: "GPS", name: "Gap Inc." },
  { symbol: "GRMN", name: "Garmin Ltd." },
  { symbol: "IT", name: "Gartner Inc" },
  { symbol: "GD", name: "General Dynamics" },
  { symbol: "GE", name: "General Electric" },
  { symbol: "GIS", name: "General Mills" },
  { symbol: "GM", name: "General Motors" },
  { symbol: "GPC", name: "Genuine Parts" },
  { symbol: "GILD", name: "Gilead Sciences" },
  { symbol: "GL", name: "Globe Life Inc." },
  { symbol: "GPN", name: "Global Payments Inc." },
  { symbol: "GS", name: "Goldman Sachs Group" },
  { symbol: "GWW", name: "Grainger (W.W.) Inc." },
  { symbol: "HAL", name: "Halliburton Co." },
  { symbol: "HBI", name: "Hanesbrands Inc" },
  { symbol: "HOG", name: "Harley-Davidson" },
  { symbol: "HIG", name: "Hartford Financial Svc.Gp." },
  { symbol: "HAS", name: "Hasbro Inc." },
  { symbol: "HCA", name: "HCA Healthcare" },
  { symbol: "HCP", name: "HCP Inc." },
  { symbol: "HP", name: "Helmerich & Payne" },
  { symbol: "HSIC", name: "Henry Schein" },
  { symbol: "HSY", name: "The Hershey Company" },
  { symbol: "HES", name: "Hess Corporation" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise" },
  { symbol: "HLT", name: "Hilton Worldwide Holdings Inc" },
  { symbol: "HFC", name: "HollyFrontier Corp" },
  { symbol: "HOLX", name: "Hologic" },
  { symbol: "HD", name: "Home Depot" },
  { symbol: "HON", name: "Honeywell Int'l Inc." },
  { symbol: "HRL", name: "Hormel Foods Corp." },
  { symbol: "HST", name: "Host Hotels & Resorts" },
  { symbol: "HPQ", name: "HP Inc." },
  { symbol: "HUM", name: "Humana Inc." },
  { symbol: "HBAN", name: "Huntington Bancshares" },
  { symbol: "HII", name: "Huntington Ingalls Industries" },
  { symbol: "IEX", name: "IDEX Corporation" },
  { symbol: "IDXX", name: "IDEXX Laboratories" },
  { symbol: "INFO", name: "IHS Markit Ltd." },
  { symbol: "ITW", name: "Illinois Tool Works" },
  { symbol: "ILMN", name: "Illumina Inc" },
  { symbol: "IR", name: "Ingersoll-Rand PLC" },
  { symbol: "INTC", name: "Intel Corp." },
  { symbol: "ICE", name: "Intercontinental Exchange" },
  { symbol: "IBM", name: "International Business Machines" },
  { symbol: "INCY", name: "Incyte" },
  { symbol: "IP", name: "International Paper" },
  { symbol: "IPG", name: "Interpublic Group" },
  { symbol: "IFF", name: "Intl Flavors & Fragrances" },
  { symbol: "INTU", name: "Intuit Inc." },
  { symbol: "ISRG", name: "Intuitive Surgical Inc." },
  { symbol: "IVZ", name: "Invesco Ltd." },
  { symbol: "IPGP", name: "IPG Photonics Corp." },
  { symbol: "IQV", name: "IQVIA Holdings Inc." },
  { symbol: "IRM", name: "Iron Mountain Incorporated" },
  { symbol: "JKHY", name: "Jack Henry & Associates" },
  { symbol: "JEC", name: "Jacobs Engineering Group" },
  { symbol: "JBHT", name: "J. B. Hunt Transport Services" },
  { symbol: "JEF", name: "Jefferies Financial Group" },
  { symbol: "SJM", name: "JM Smucker" },
  { symbol: "JNJ", name: "Johnson & Johnson" },
  { symbol: "JCI", name: "Johnson Controls International" },
  { symbol: "JPM", name: "JPMorgan Chase & Co." },
  { symbol: "JNPR", name: "Juniper Networks" },
  { symbol: "KSU", name: "Kansas City Southern" },
  { symbol: "K", name: "Kellogg Co." },
  { symbol: "KEY", name: "KeyCorp" },
  { symbol: "KEYS", name: "Keysight Technologies" },
  { symbol: "KMB", name: "Kimberly-Clark" },
  { symbol: "KIM", name: "Kimco Realty" },
  { symbol: "KMI", name: "Kinder Morgan" },
  { symbol: "KLAC", name: "KLA Corporation" },
  { symbol: "KSS", name: "Kohl's Corp." },
  { symbol: "KHC", name: "Kraft Heinz Co" },
  { symbol: "KR", name: "Kroger Co." },
  { symbol: "LB", name: "L Brands Inc." },
  { symbol: "LHX", name: "L3Harris Technologies" },
  { symbol: "LH", name: "Laboratory Corp. of America Holding" },
  { symbol: "LRCX", name: "Lam Research" },
  { symbol: "LW", name: "Lamb Weston Holdings Inc" },
  { symbol: "LEG", name: "Leggett & Platt" },
  { symbol: "LDOS", name: "Leidos Holdings" },
  { symbol: "LEN", name: "Lennar Corp." },
  { symbol: "LLY", name: "Lilly (Eli) & Co." },
  { symbol: "LNC", name: "Lincoln National" },
  { symbol: "LIN", name: "Linde plc" },
  { symbol: "LKQ", name: "LKQ Corporation" },
  { symbol: "LMT", name: "Lockheed Martin Corp." },
  { symbol: "L", name: "Loews Corp." },
  { symbol: "LOW", name: "Lowe's Cos." },
  { symbol: "LYB", name: "LyondellBasell" },
  { symbol: "MTB", name: "M&T Bank Corp." },
  { symbol: "MAC", name: "Macerich" },
  { symbol: "M", name: "Macy's Inc." },
  { symbol: "MRO", name: "Marathon Oil Corp." },
  { symbol: "MPC", name: "Marathon Petroleum" },
  { symbol: "MKTX", name: "MarketAxess" },
  { symbol: "MAR", name: "Marriott Int'l." },
  { symbol: "MMC", name: "Marsh & McLennan" },
  { symbol: "MLM", name: "Martin Marietta Materials" },
  { symbol: "MAS", name: "Masco Corp." },
  { symbol: "MA", name: "Mastercard Inc." },
  { symbol: "MKC", name: "McCormick & Co." },
  { symbol: "MXIM", name: "Maxim Integrated Products Inc" },
  { symbol: "MCD", name: "McDonald's Corp." },
  { symbol: "MCK", name: "McKesson Corp." },
  { symbol: "MDT", name: "Medtronic plc" },
  { symbol: "MRK", name: "Merck & Co." },
  { symbol: "MET", name: "MetLife Inc." },
  { symbol: "MTD", name: "Mettler Toledo" },
  { symbol: "MGM", name: "MGM Resorts International" },
  { symbol: "MCHP", name: "Microchip Technology" },
  { symbol: "MU", name: "Micron Technology" },
  { symbol: "MSFT", name: "Microsoft Corp." },
  { symbol: "MAA", name: "Mid-America Apartments" },
  { symbol: "MHK", name: "Mohawk Industries" },
  { symbol: "TAP", name: "Molson Coors Brewing Company" },
  { symbol: "MDLZ", name: "Mondelez International" },
  { symbol: "MNST", name: "Monster Beverage" },
  { symbol: "MCO", name: "Moody's Corp" },
  { symbol: "MS", name: "Morgan Stanley" },
  { symbol: "MOS", name: "The Mosaic Company" },
  { symbol: "MSI", name: "Motorola Solutions Inc." },
  { symbol: "MSCI", name: "MSCI Inc" },
  { symbol: "MYL", name: "Mylan N.V." },
  { symbol: "NDAQ", name: "Nasdaq, Inc." },
  { symbol: "NOV", name: "National Oilwell Varco Inc." },
  { symbol: "NKTR", name: "Nektar Therapeutics" },
  { symbol: "NTAP", name: "NetApp" },
  { symbol: "NFLX", name: "Netflix Inc." },
  { symbol: "NWL", name: "Newell Brands" },
  { symbol: "NEM", name: "Newmont Goldcorp" },
  { symbol: "NWSA", name: "News Corp. Class A" },
  { symbol: "NWS", name: "News Corp. Class B" },
  { symbol: "NEE", name: "NextEra Energy" },
  { symbol: "NLSN", name: "Nielsen Holdings" },
  { symbol: "NKE", name: "Nike" },
  { symbol: "NI", name: "NiSource Inc." },
  { symbol: "NBL", name: "Noble Energy Inc" },
  { symbol: "JWN", name: "Nordstrom" },
  { symbol: "NSC", name: "Norfolk Southern Corp." },
  { symbol: "NTRS", name: "Northern Trust Corp." },
  { symbol: "NOC", name: "Northrop Grumman" },
  { symbol: "NCLH", name: "Norwegian Cruise Line Holdings" },
  { symbol: "NRG", name: "NRG Energy" },
  { symbol: "NUE", name: "Nucor Corp." },
  { symbol: "NVDA", name: "Nvidia Corporation" },
  { symbol: "ORLY", name: "O'Reilly Automotive" },
  { symbol: "OXY", name: "Occidental Petroleum" },
  { symbol: "OMC", name: "Omnicom Group" },
  { symbol: "OKE", name: "ONEOK" },
  { symbol: "ORCL", name: "Oracle Corp." },
  { symbol: "PCAR", name: "PACCAR Inc." },
  { symbol: "PKG", name: "Packaging Corporation of America" },
  { symbol: "PH", name: "Parker-Hannifin" },
  { symbol: "PAYX", name: "Paychex Inc." },
  { symbol: "PYPL", name: "PayPal" },
  { symbol: "PNR", name: "Pentair plc" },
  { symbol: "PBCT", name: "People's United Financial" },
  { symbol: "PEP", name: "PepsiCo Inc." },
  { symbol: "PKI", name: "PerkinElmer" },
  { symbol: "PRGO", name: "Perrigo" },
  { symbol: "PFE", name: "Pfizer Inc." },
  { symbol: "PM", name: "Philip Morris International" },
  { symbol: "PSX", name: "Phillips 66" },
  { symbol: "PNW", name: "Pinnacle West Capital" },
  { symbol: "PXD", name: "Pioneer Natural Resources" },
  { symbol: "PNC", name: "PNC Financial Services" },
  { symbol: "PPG", name: "PPG Industries" },
  { symbol: "PPL", name: "PPL Corp." },
  { symbol: "PFG", name: "Principal Financial Group" },
  { symbol: "PG", name: "Procter & Gamble" },
  { symbol: "PGR", name: "Progressive Corp." },
  { symbol: "PLD", name: "Prologis" },
  { symbol: "PRU", name: "Prudential Financial" },
  { symbol: "PEG", name: "Public Serv. Enterprise Inc." },
  { symbol: "PSA", name: "Public Storage" },
  { symbol: "PHM", name: "Pulte Homes Inc." },
  { symbol: "PVH", name: "PVH Corp." },
  { symbol: "QRVO", name: "Qorvo" },
  { symbol: "PWR", name: "Quanta Services Inc." },
  { symbol: "QCOM", name: "QUALCOMM Inc." },
  { symbol: "DGX", name: "Quest Diagnostics" },
  { symbol: "RL", name: "Ralph Lauren Corporation" },
  { symbol: "RJF", name: "Raymond James Financial Inc." },
  { symbol: "RTN", name: "Raytheon Co." },
  { symbol: "O", name: "Realty Income Corporation" },
  { symbol: "REG", name: "Regency Centers Corporation" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals" },
  { symbol: "RF", name: "Regions Financial Corp." },
  { symbol: "RSG", name: "Republic Services Inc" },
  { symbol: "RMD", name: "ResMed" },
  { symbol: "RHI", name: "Robert Half International" },
  { symbol: "ROK", name: "Rockwell Automation Inc." },
  { symbol: "ROL", name: "Rollins Inc." },
  { symbol: "ROP", name: "Roper Technologies" },
  { symbol: "ROST", name: "Ross Stores" },
  { symbol: "RCL", name: "Royal Caribbean Cruises Ltd" },
  { symbol: "CRM", name: "Salesforce.com" },
  { symbol: "SBAC", name: "SBA Communications" },
  { symbol: "SLB", name: "Schlumberger Ltd." },
  { symbol: "STX", name: "Seagate Technology" },
  { symbol: "SEE", name: "Sealed Air" },
  { symbol: "SRE", name: "Sempra Energy" },
  { symbol: "SHW", name: "Sherwin-Williams" },
  { symbol: "SPG", name: "Simon Property Group Inc" },
  { symbol: "SWKS", name: "Skyworks Solutions" },
  { symbol: "SLG", name: "SL Green Realty" },
  { symbol: "SNA", name: "Snap-on" },
  { symbol: "SO", name: "Southern Co." },
  { symbol: "LUV", name: "Southwest Airlines" },
  { symbol: "SPGI", name: "S&P Global, Inc." },
  { symbol: "SWK", name: "Stanley Black & Decker" },
  { symbol: "SBUX", name: "Starbucks Corp." },
  { symbol: "STT", name: "State Street Corp." },
  { symbol: "SYK", name: "Stryker Corp." },
  { symbol: "STI", name: "SunTrust Banks" },
  { symbol: "SIVB", name: "SVB Financial" },
  { symbol: "SYMC", name: "Symantec Corp." },
  { symbol: "SYF", name: "Synchrony Financial" },
  { symbol: "SNPS", name: "Synopsys Inc." },
  { symbol: "SYY", name: "Sysco Corp." },
  { symbol: "TMUS", name: "T-Mobile US" },
  { symbol: "TROW", name: "T. Rowe Price Group" },
  { symbol: "TTWO", name: "Take-Two Interactive" },
  { symbol: "TPR", name: "Tapestry, Inc." },
  { symbol: "TGT", name: "Target Corp." },
  { symbol: "TEL", name: "TE Connectivity Ltd." },
  { symbol: "FTI", name: "TechnipFMC" },
  { symbol: "TFX", name: "Teleflex" },
  { symbol: "TXN", name: "Texas Instruments" },
  { symbol: "TXT", name: "Textron Inc." },
  { symbol: "TMO", name: "Thermo Fisher Scientific" },
  { symbol: "TIF", name: "Tiffany & Co." },
  { symbol: "TWTR", name: "Twitter, Inc." },
  { symbol: "TJX", name: "TJX Companies Inc." },
  { symbol: "TSS", name: "Total System Services" },
  { symbol: "TSCO", name: "Tractor Supply Company" },
  { symbol: "TDG", name: "TransDigm Group" },
  { symbol: "TRV", name: "The Travelers Companies Inc." },
  { symbol: "TRIP", name: "TripAdvisor" },
  { symbol: "TSN", name: "Tyson Foods" },
  { symbol: "UDR", name: "UDR, Inc." },
  { symbol: "ULTA", name: "Ulta Beauty" },
  { symbol: "USB", name: "U.S. Bancorp" },
  { symbol: "UAA", name: "Under Armour Class A" },
  { symbol: "UA", name: "Under Armour Class C" },
  { symbol: "UNP", name: "Union Pacific Corp" },
  { symbol: "UAL", name: "United Airlines Holdings" },
  { symbol: "UNH", name: "United Health Group Inc." },
  { symbol: "UPS", name: "United Parcel Service" },
  { symbol: "URI", name: "United Rentals, Inc." },
  { symbol: "UTX", name: "United Technologies" },
  { symbol: "UHS", name: "Universal Health Services, Inc." },
  { symbol: "UNM", name: "Unum Group" },
  { symbol: "VFC", name: "V.F. Corp." },
  { symbol: "VLO", name: "Valero Energy" },
  { symbol: "VAR", name: "Varian Medical Systems" },
  { symbol: "VTR", name: "Ventas Inc" },
  { symbol: "VRSN", name: "Verisign Inc." },
  { symbol: "VRSK", name: "Verisk Analytics" },
  { symbol: "VZ", name: "Verizon Communications" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals Inc" },
  { symbol: "VIAB", name: "Viacom Inc." },
  { symbol: "V", name: "Visa Inc." },
  { symbol: "VNO", name: "Vornado Realty Trust" },
  { symbol: "VMC", name: "Vulcan Materials" },
  { symbol: "WAB", name: "Wabtec Corporation" },
  { symbol: "WMT", name: "Walmart" },
  { symbol: "WBA", name: "Walgreens Boots Alliance" },
  { symbol: "DIS", name: "The Walt Disney Company" },
  { symbol: "WM", name: "Waste Management Inc." },
  { symbol: "WAT", name: "Waters Corporation" },
  { symbol: "WEC", name: "Wec Energy Group Inc" },
  { symbol: "WCG", name: "WellCare" },
  { symbol: "WFC", name: "Wells Fargo" },
  { symbol: "WELL", name: "Welltower Inc." },
  { symbol: "WDC", name: "Western Digital" },
  { symbol: "WU", name: "Western Union Co" },
  { symbol: "WRK", name: "WestRock" },
  { symbol: "WY", name: "Weyerhaeuser" },
  { symbol: "WHR", name: "Whirlpool Corp." },
  { symbol: "WMB", name: "Williams Cos." },
  { symbol: "WLTW", name: "Willis Towers Watson" },
  { symbol: "WYNN", name: "Wynn Resorts Ltd" },
  { symbol: "XEL", name: "Xcel Energy Inc" },
  { symbol: "XRX", name: "Xerox" },
  { symbol: "XLNX", name: "Xilinx" },
  { symbol: "XYL", name: "Xylem Inc." },
  { symbol: "YUM", name: "Yum! Brands Inc" },
  { symbol: "ZBH", name: "Zimmer Biomet Holdings" },
  { symbol: "ZION", name: "Zions Bancorp" },
  { symbol: "ZTS", name: "Zoetis" },
]

companies.sort((a, b) => (a.symbol > b.symbol) ? 1 : -1)

export default class CompanyList {

  static list() {
    return companies;
  }

  static find(index) {
    return companies[index];
  }

  static findBySymbol(symbol) {
    const company = companies.find(c => c.symbol === symbol);
    return company;
  }

}